CinemaProject/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CinemaProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

CinemaProject/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CinemaProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return RedirectToPage("/Customer/Home/Index");
		}
	}
}

CinemaProject/Pages/Login.cshtml.cs
using CinemaProject.Pages.PageViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CinemaProject.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        [BindProperty]
        public Login Login { get; set; }

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Login.EmailAddress, Login.Password, Login.RememberMe, false);
                if (result.Succeeded)
                    return RedirectToPage("Index");
                else
                {
                    ModelState.AddModelError("", "Username or Password is incorrect");
                    return Page();
                }
            }
            return RedirectToPage("Index");
        }
    }
}

CinemaProject/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CinemaProject.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("Index");
        }

        public IActionResult OnPostNoLogout()
        {
            return RedirectToPage("Index");
        }
    }
}

CinemaProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CinemaProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

CinemaProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CinemaProject/Pages/Login.cshtml
@page
@model CinemaProject.Pages.LoginModel
@{
}
<form method="post">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary pl-3">
                Login
            </h2>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Login.EmailAddress"></label>
            <input asp-for="@Model.Login.EmailAddress" class="form-control" />
            <span asp-validation-for="Login.EmailAddress" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Login.Password"></label>
            <input asp-for="@Model.Login.Password" class="form-control" />
            <span asp-validation-for="Login.Password" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Login.RememberMe"></label>
            <input type="checkbox" asp-for="@Model.Login.RememberMe" class="form-check" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Login</button>
            <a asp-page="Index" button type="submit" class="btn btn-outline-secondary">Home</a>
        </div>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_validationScriptsPartial" />
    }
}

CinemaProject/Pages/Logout.cshtml
@page
@model CinemaProject.Pages.LogoutModel
@{
}
<form method="post">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary pl-3">
                Logout
            </h2>
        </div>
        <div class="mb-3">
            <p>Are you sure you want to logout</p>
            <p>
                <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                <button class="btn btn-outline-secondary ml-5" asp-page-handler="NoLogout">No</button>
            </p>
        </div>
    </div>
</form>